#!/usr/bin/env bash
set -euo pipefail

# Publish daily robotics digest markdown files into a Chirpy/Jekyll site as posts.
# - Source (generated by OpenClaw):
#     ~/prog/OpenClaw/docs/Chinese/robotics_digest_YYYY-MM-DD.md
#     ~/prog/OpenClaw/docs/English/robotics_digest_YYYY-MM-DD.md
# - Destination (this repo):
#     _posts/digests/YYYY-MM-DD-robotics-digest-cn(.md|_v2.md...)
#     _posts/digests/YYYY-MM-DD-robotics-digest-en(.md|_v2.md...)

DATE="${1:-}"
if [[ -z "$DATE" ]]; then
  DATE="$(date +%F)"
fi

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

CN_SRC="$HOME/prog/OpenClaw/docs/Chinese/robotics_digest_${DATE}.md"
EN_SRC="$HOME/prog/OpenClaw/docs/English/robotics_digest_${DATE}.md"

POST_DIR="$REPO_DIR/_posts/digests"
mkdir -p "$POST_DIR"

next_name() {
  local base="$1"
  if [[ ! -e "$base" ]]; then
    echo "$base"; return
  fi
  local i=2
  while true; do
    local cand="${base%.md}_v${i}.md"
    if [[ ! -e "$cand" ]]; then
      echo "$cand"; return
    fi
    i=$((i+1))
  done
}

write_post() {
  local lang="$1" src="$2" base="$3" title="$4" tag="$5"

  if [[ ! -f "$src" ]]; then
    echo "ERROR: source file not found: $src" >&2
    exit 2
  fi

  local dst
  dst="$(next_name "$base")"

  {
    echo "---"
    echo "title: \"${title}\""
    echo "date: ${DATE} 00:00:00 +0800"
    echo "categories: [Digest, Robotics]"
    echo "tags: [robotics, market, arxiv, ${tag}]"
    echo "---"
    echo
    cat "$src"
  } > "$dst"

  echo "$dst"
}

CN_BASE="$POST_DIR/${DATE}-robotics-digest-cn.md"
EN_BASE="$POST_DIR/${DATE}-robotics-digest-en.md"

CN_DST="$(write_post cn "$CN_SRC" "$CN_BASE" "Robotics Digest (CN) — ${DATE}" cn)"
EN_DST="$(write_post en "$EN_SRC" "$EN_BASE" "Robotics Digest (EN) — ${DATE}" en)"

cd "$REPO_DIR"

# Commit & push
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git add "$CN_DST" "$EN_DST"
  if ! git diff --cached --quiet; then
    git commit -m "Add robotics digests (${DATE})"
    git push
  else
    echo "No changes to commit."
  fi
else
  echo "ERROR: not a git repo: $REPO_DIR" >&2
  exit 3
fi

echo "Published:"
echo "- $CN_DST"
echo "- $EN_DST"
